//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cms
{
    using System;
    using System.Collections.Generic;
    
    public partial class GraveOwner
    {
        public System.Guid ObjId { get; set; }
        public Nullable<System.Guid> GraveId { get; set; }
        public Nullable<System.Guid> ApplicationId { get; set; }
    }
}
