//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cms
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportHeader
    {
        public System.Guid ObjId { get; set; }
        public string OrganisationName { get; set; }
        public string Address { get; set; }
        public string TeNo { get; set; }
        public string Vat { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
