//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cms
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteVisitAudit
    {
        public System.Guid ObjId { get; set; }
        public Nullable<System.DateTime> DateOfVisit { get; set; }
        public string Purpose { get; set; }
        public string Officer { get; set; }
        public Nullable<bool> GraveFound { get; set; }
    }
}
